name: ly_na
description: application E-learning flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  #flutter_stripe: ^9.5.0
  google_fonts: ^6.1.0
  dio: ^5.4.0
  path_provider: ^2.1.2
  open_file: ^3.3.2

  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.2.0
  flutter_file_dialog: ^3.0.2
  http: ^1.4.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  jitsi_meet_wrapper: ^0.2.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/