// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIJ6a0csgKV80dCVilBcWFdOUc8LApsM',
    appId: '1:8037973642:web:e949b620ff5f6b4a3e7773',
    messagingSenderId: '8037973642',
    projectId: 'version2-a3872',
    authDomain: 'version2-a3872.firebaseapp.com',
    storageBucket: 'version2-a3872.firebasestorage.app',
    measurementId: 'G-3KF4J191NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlC76PrjRe1eERhC8Wzu0UdCJVeiKJAec',
    appId: '1:8037973642:android:45c16ea8523f4cfe3e7773',
    messagingSenderId: '8037973642',
    projectId: 'version2-a3872',
    storageBucket: 'version2-a3872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Isi0XnmVvHlKu7PusKcePv-Q_OHiYxg',
    appId: '1:8037973642:ios:d2f7dce8482e431b3e7773',
    messagingSenderId: '8037973642',
    projectId: 'version2-a3872',
    storageBucket: 'version2-a3872.firebasestorage.app',
    iosBundleId: 'com.example.lyNa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Isi0XnmVvHlKu7PusKcePv-Q_OHiYxg',
    appId: '1:8037973642:ios:d2f7dce8482e431b3e7773',
    messagingSenderId: '8037973642',
    projectId: 'version2-a3872',
    storageBucket: 'version2-a3872.firebasestorage.app',
    iosBundleId: 'com.example.lyNa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyIJ6a0csgKV80dCVilBcWFdOUc8LApsM',
    appId: '1:8037973642:web:b16cb62f8d3eb7f33e7773',
    messagingSenderId: '8037973642',
    projectId: 'version2-a3872',
    authDomain: 'version2-a3872.firebaseapp.com',
    storageBucket: 'version2-a3872.firebasestorage.app',
    measurementId: 'G-8N15BCF7CW',
  );

}